name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build Docker image
      run: docker build -t simple-java-app:latest .

    - name: Tag Docker image
      run: docker tag simple-java-app:latest adirwaitzman/simple-java-app:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push adirwaitzman/simple-java-app:latest


  increment_version:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}
    steps:
    - name: version increanent
      uses: action-pack/increment@v2
      with:
        name: 'VERSION'
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
